## Checkm2

```{r checkm2, echo = F, message = F, warning = F, error = T}





# Read raw input
checkm2_raw = read_tsv(glob_list$checkm2)

checkm2_presentable = metadata_translate %>%
    select(sample) %>%
    left_join(checkm2_raw, by = c("sample" = "Name")) %>%
    
    mutate(
        #Completeness_Model_Used = str_replace(Completeness_Model_Used, "Neural Network", "NN"),
        Average_Gene_Length = round(Average_Gene_Length, 1)
    ) %>%
    rename_with(str_replace_all, pattern = "_", replacement = " ")
    

checkm2_presentable %>%
    custom_dt("checkm2")


```

*Table `r tableno()`: [Checkm2](https://github.com/chklovski/CheckM2) results. *



```{r checkm2_plot, echo=FALSE, message=F, warning=F, error = T, fig.height = 4.8, fig.width = 10}

checkm2_presentable %>%
    ggplot(aes(Completeness, Contamination, color = `Coding Density`, label = sample)) +
    geom_point() +
    geom_text(color = "black", alpha = 0.5, check_overlap = T, hjust = 0, vjust = 0, size = 2.5) +
    labs(
        x = "Completeness [%]",
        y = "Contamination [%]") +
    scale_color_viridis_b() +
    theme_bw()

```

```{r checkm2_plot_new, echo=FALSE, message=F, warning=F, error = T, fig.height = 4.8, fig.width = 10}

# New better plot. 
# checkm2_presentable  %>% 

#     select(sample, Completeness, Contamination, `Completeness Model Used`) %>%
#     pivot_longer(c(Completeness, Contamination))  %>% 

#     ggplot(aes(value, sample)) + 
#     geom_col() +
#     facet_wrap(~name)
    #scale_x_reverse()


left = checkm2_presentable  %>% 
    select(sample, Completeness, Contamination, `Completeness Model Used`) %>%
    ggplot(aes(Contamination, sample)) + 
    geom_col(fill = "yellow") +
    scale_x_reverse()

right = checkm2_presentable  %>% 
    select(sample, Completeness, Contamination, `Completeness Model Used`) %>%
    ggplot(aes(Completeness, sample)) + 
    geom_col(fill = "blue") +
    scale_x_reverse()


grid.draw(ggplotGrob(left))
md_inset <- viewport(x = 0, y = 0, 
                     just = c("left", "bottom"),
                     width = 0.35, height = 0.35)
pushViewport(md_inset)
grid.draw(rectGrob(gp = gpar(alpha = 0.5, col = "white")))
grid.draw(rectGrob(gp = gpar(fill = NA, col = "black")))
grid.draw(ggplotGrob(right))
popViewport()


```





*Fig. `r figno()`: [Checkm2](https://github.com/chklovski/CheckM2) results. Axes are in percents. Colored by coding density. Samples in the lower right corner are relatively better.*


---