#!/usr/bin/env python

__author__ = "Carl M. Kobel"


# --- Development: Versioning ---------------------------------------
__version__ = "2.10.1"
# Places to bump
#  - here
#  - workflow/Snakefile, because the snakefile can possibly be run without the ./comparem2 binary. Report gets from here.
#  - changelog
# Also, paste changelog into the github release. Use pre-release and publish it after it has been tested.


# --- Development: Testing "nightly" --------------------------------

# For developing and testing (using conda) prior to publication of next version apptainer image, you can run the following from the repository directory:
# Conda
# export COMPAREM2_BASE="$(realpath ~/comparem2)"; export COMPAREM2_PROFILE="${COMPAREM2_BASE}/profile/conda/default"; ${COMPAREM2_BASE}/comparem2 --config input_genomes="${COMPAREM2_BASE}/tests/E._faecium/*.fna" --until fast

# If you haven't made any changes to the environment yamls, you can test using the apptainer/docker image.
# Apptainer
# export COMPAREM2_BASE="$(realpath ~/comparem2)"; export COMPAREM2_PROFILE="${COMPAREM2_BASE}/profile/apptainer/default"; ${COMPAREM2_BASE}/comparem2 --config input_genomes="${COMPAREM2_BASE}/tests/E._faecium/*.fna" --until fast


# --- Development: Update Dockerfile --------------------------------
# Update Dockerfile:
# export COMPAREM2_BASE="$(pwd -P)"; export COMPAREM2_PROFILE="profiles/apptainer/default"; snakemake --snakefile "${COMPAREM2_BASE}/workflow/Snakefile" --configfile "${COMPAREM2_BASE}/config/config.yaml" --containerize | grep -A 10000 "FROM condaforge" > Dockerfile
# And then remove the header text (comparem2 logo, etc.) if necessary
# In the future I will make my docker images myself:
# sudo docker build -t cmkobel/comparem2:v2.10 . && sudo docker push cmkobel/comparem2:v2.10

# In case the exact same docker image should be used for consecutive versions of comparem2: (example)
# sudo docker pull cmkobel/comparem2:v2.9
# sudo docker tag cmkobel/comparem2:v2.9 cmkobel/comparem2:v2.10
# sudo docker push cmkobel/comparem2:v2.10


# --- Development: Update DAG figure for documentation --------------
# Update dag picture in documentation with this command (with anaconda/graphviz)
# comparem2 --forceall --rulegraph | dot -Tpng > dag.png

"""
This is the launcher script for comparem2.

It has two main functions.
1) It checks that the necessary environment variables has been set. If not, it uses reasonable defaults.
2) Then it calls the snakemake pipeline using the command line arguments passed to this here script.

Because any command line arguments are passed directly to the subprocess.run()-snakemake call in the bottom of this script, you can use any snakemake-compatible command line argument to this script. E.g: `comparem2 --dry-run`.

This "binary" file works instead of the alias that has been previously used.

"""


import logging
import os 
import sys
import subprocess
import shutil


# Create logger that prints to the terminal.
logger = logging.getLogger('comparem2_launcher')
logger.setLevel(logging.INFO)
console_handler = logging.StreamHandler()
#console_handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console_handler.setFormatter(formatter)
logger.addHandler(console_handler)






# Read system variables and use defaults if necessary.

# Sets the COMPAREM2_BASE to the directory of this python script file which (script file) should be neighboring the correct snakefile.
try:
    COMPAREM2_BASE = os.environ['COMPAREM2_BASE']
    logger.debug(f"COMPAREM2_BASE was already set to \"{COMPAREM2_BASE}\".")
except KeyError as e:
    COMPAREM2_BASE = os.path.dirname(os.path.realpath(__file__)) # This seems to work even for symlinks (it gets the physical path.). Update: Maybe that is why the apptainer environment can't find the cwd?
    os.environ["COMPAREM2_BASE"] = COMPAREM2_BASE
    logger.debug(f"COMPAREM2_BASE was not set and has been defaulted to \"{COMPAREM2_BASE}\".")

# Defines the COMPAREM2_PROFILE relative to the COMPAREM2_BASE if not set already.
# Detects and prioritizes to use apptainer if it exists.
try:
    COMPAREM2_PROFILE = os.environ['COMPAREM2_PROFILE']
    logger.debug(f"COMPAREM2_PROFILE was already set to \"{COMPAREM2_PROFILE}\".")
except KeyError as e: # The profile has not been set.
    # We might check whether apptainer is present. If it is we will use it, if not, we'll use conda.
    if shutil.which("apptainer") is not None: # Apptainer exists, use it.
        COMPAREM2_PROFILE = f"{COMPAREM2_BASE}/profile/apptainer/default"
        logger.debug(f"Using apptainer.")
    else: 
        COMPAREM2_PROFILE = f"{COMPAREM2_BASE}/profile/conda/default"
        logger.debug(f"Using conda.")
    
    os.environ["COMPAREM2_PROFILE"] = COMPAREM2_PROFILE
    logger.debug(f"COMPAREM2_PROFILE was not set and has been defaulted to \"{COMPAREM2_PROFILE}\".")

# Defines the COMPAREM2_DATABASES relative to the COMPAREM2_BASE if not set already.
try:
    COMPAREM2_DATABASES = os.environ['COMPAREM2_DATABASES']
    logger.debug(f"COMPAREM2_DATABASES was already set to \"{COMPAREM2_DATABASES}\".")
except KeyError as e:
    COMPAREM2_DATABASES = f"{COMPAREM2_BASE}/databases"
    os.environ["COMPAREM2_DATABASES"] = COMPAREM2_DATABASES
    logger.debug(f"COMPAREM2_DATABASES was not set and has been defaulted to \"{COMPAREM2_DATABASES}\".")




# Then call the pipeline (alias) using the variables that have just been set, including the command line parameters that have been passed to this script. As we have already saved the new environment variables with os.environ(), we can just call as is.

# I will have to check whether this will work for both conda and apptainer based installations? It should. In the test on bioconda I should use conda (not apptainer).

# Concatenate the trailing command line arguments to add to the snakemake command.
trailing_arguments = sys.argv[1:]
trailing_arguments_concatenated = " ".join(trailing_arguments)
logger.debug(f"The concatenated trailing arguments are {trailing_arguments_concatenated}")

command_main = f"snakemake --snakefile \"{COMPAREM2_BASE}\"/workflow/Snakefile --profile \"{COMPAREM2_PROFILE}\" --configfile \"{COMPAREM2_BASE}\"/config/config.yaml  " + trailing_arguments_concatenated
logger.debug(f"Command to run is\n{command_main}")

command_report = f"""snakemake --snakefile "$COMPAREM2_BASE/dynamic_report/workflow/Snakefile" --profile "$COMPAREM2_PROFILE" --configfile=.report_config.yaml"""




# Finally, run the pipeline.


if "--version" in trailing_arguments or "-v" in trailing_arguments:
    print(f"comparem2 v{__version__}")
    
elif "--help" in trailing_arguments or "-h" in trailing_arguments:
    #print(help_message)
    with open(COMPAREM2_BASE + "/docs/help_text.txt") as file:
        for line in file:
            print(line, end = "")
    print()


elif "--cite" in trailing_arguments:
    print("If you use CompareM2, you can support further funding by bumping the citation count on this one:\n\n\tKobel, C. M. et al. CompareM2 is a genomes-to-report pipeline for comparing microbial genomes. 2024.07.12.603264 Preprint at https://doi.org/10.1101/2024.07.12.603264 (2024).\n\nCompareM2 would not have existed, if it hadn't been for the integrated software packages and their databases. Please cite the appropriate tools as well. An up to date list is maintained here: https://comparem2.readthedocs.io/en/latest/99%20citation/\n")

    
else:
    # Run comparem2 main pipeline
    process_main = subprocess.run(command_main, shell = True)
    returncode_main = process_main.returncode
    
    # Run dynamic report pipeline   
    # Only run report if there is metadata and something is worth rendering.
    # if os.path.isfile("{output_directory}/metadata.tsv") and os.path.isfile("{output_directory}/.comparem2_void_report.flag"):  # Should be moved to the report pipeline itself.
    
    if os.path.isfile(".report_config.yaml"):
        process_report = subprocess.run(command_report, shell = True)
        returncode_report = process_report.returncode
    else:
        print("Pipeline: .report_config.yaml has not yet been created.") # This happens when doing a dry-run in a new dir.
        
    # Exit with the return code of the main pipeline.
    sys.exit(returncode_main)
    