name: comparem2_launcher
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake >=9.16
  - snakemake-executor-plugin-cluster-generic
  - mamba
  - conda
  - pandas

# This file is replaced by resources/env_current.yaml

# This file should always mirror: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/comparem2/meta.yaml
