name: comparem2_launcher
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal <8
  - pulp <2.8 # What is this for?
  - python <3.12
  - mamba <2 # Necessary for snakemake to install child environments during development.
  - pandas

# This file is replaced by resources/env_current.yaml

# This file should always mirror: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/comparem2/meta.yaml
