site_name: CompareM2
site_description: Documentation for CompareM2 the genomes-to-report pipeline 
copyright: [comparem2](https://github.com/cmkobel/CompareM2) genomes-to-report pipeline. Copyright © 2019-2025 GNU GPL v3
nav:
  - "index.md"
  - "05 quick start.md"
  - "10 installation.md"
  - "20 usage.md"
  - "30 what analyses does it do.md"
  - "80 future functionality.md"
  - "82 contributors.md"
  - "99 citation.md"
site_url: https://comparem2.readthedocs.io/
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
repo_url: https://github.com/cmkobel/comparem2

