site_name: CompareM2
site_description: Documentation for CompareM2 the genomes-to-report pipeline 
copyright: CompareM2 genomes-to-report pipeline. Copyright © 2019-2025 GNU GPL v3
nav:
  - Home: "index.md"
  - "Quick start": "05 quick start.md"
  - Installation: "10 installation.md"
  - Usage: "20 usage.md"
  - "What": "30 what analyses does it do.md"
  - "Future functionality": "80 future functionality.md"
  - "Contributors": "82 contributors.md"
  - "Citing and alternatives": "99 citation.md"
site_url: https://comparem2.readthedocs.io/
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
repo_url: https://github.com/cmkobel/comparem2

