site_name: CompareM2
copyright: (c) cmkobel 2019-2024
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
repo_url: https://github.com/cmkobel/comparem2

