[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "assemblycomparator2"
authors = [{name = "Carl M. Kobel", email = "carl.mathias.kobel@nmbu.no"}]
dynamic = ["2.6.2", "Genomes to report pipeline"]
