# Resources
cores: all

# Policies
keep-going: true 
rerun-incomplete: true
show-failed-logs: false
rerun-triggers: "mtime" # Only rerun on changes in modification time. Not on code hash changes.
keep-incomplete: true # true for debugging


# Conda
use-conda: true
conda-frontend: mamba
conda-prefix: '~/.asscom2/conda'






# Local setup for a typical workstation
resources:
  - mem_mb=549755
