# Resources
cores: all

# Policies
keep-going: true 
rerun-incomplete: true
show-failed-logs: false
rerun-triggers: "mtime" # Only rerun on changes in modification time. Not on code hash changes.
keep-incomplete: true #false # true for debugging. Must be false for production, otherwise the user might get confusing --rerun-incomplete queries.
rerun-incomplete: true


# Conda
use-conda: true
conda-frontend: mamba
conda-prefix: '~/.comparem2/conda'







resources:
  - downloads=20
#  - mem_mb=512000
  
