
local-cores: 8 # front end / head node cores
cores: 2048 # cluster cores
jobs: 1000 # max parallel jobs


keep-going: true 
#rerun-incomplete: true
latency-wait: 30
keep-incomplete: false # true for debugging. Must be false for production, otherwise the user might get confusing --rerun-incomplete queries.
rerun-triggers: "mtime" # only schedule jobs to rerun if there has been a change in mtime of input/output files. That is: ignore code changes
rerun-incomplete: true





# ---- Conda/Mamba ----
use-conda: true


conda-frontend: 'mamba'
conda-prefix: '~/.comparem2/conda'



# ---- Sigma2 Saga SLURM specifics ----

cluster-cancel: "scancel"


cluster:
  mkdir -p .snakemake/log/old/ &&
  sbatch
    --parsable
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=cm2_{rule}_{wildcards}
    --output=.snakemake/log/%j-{rule}.out.log
    --error=.snakemake/log/%j-{rule}.err.log
    --time={resources.runtime}
    --account=YOURACCOUNTNAMEHERE

 
    

default-resources:
  - mem_mb=1024
  - runtime='12h'
  
  