
local-cores: 16 # front end / head node cores
cores: 2048 # cluster cores
jobs: 1000 # max parallel jobs


keep-going: true 
#rerun-incomplete: true
latency-wait: 30
keep-incomplete: false # true for debugging. Must be false for production, otherwise the user might get confusing --rerun-incomplete queries.
rerun-triggers: "mtime" # only schedule jobs to rerun if there has been a change in mtime of input/output files. That is: ignore code changes
rerun-incomplete: true

# This one could be cool to have working
show-failed-logs: true

# Software deployment
software-deployment-method:
  - conda
conda-prefix: '~/.comparem2/conda'



# ---- QUT CMR Lyra specifics ----

executor: cluster-generic

cluster-generic-submit-cmd:
  qsub
    -V
    -A $USER
    -q YOURACCOUNTNAMEHERE
    -e .snakemake/log/%j-{rule}.err.log
    -o .snakemake/log/%j-{rule}.out.log
    -l select=1:ncpus={threads}:mem={resources.mem_mb}mb,walltime={resources.runtime}

cluster-generic-cancel-cmd: qdel
cluster-generic-status-cmd: "qstat -f {jobid}"

 




default-resources:
  - mem_mb=1024
  - runtime='12h'
  
  

