FROM mambaorg/micromamba:1.4.2
COPY --chown=$MAMBA_USER:$MAMBA_USER conda_definitions/abricate.yaml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes

## Inspired heavily from
# https://github.com/mamba-org/micromamba-docker#quick-start

