

input_genomes: "*.fna *.fa *.fasta *.fas" # Default value. Does not support advanced glob brace expansion. If you give multiple files or a single file has spaces or weird characters, it should be quoted within apostrophes.
annotator: "prokka" # prokka|bakta # Affects .faa used in dbcan, interproscan, diamond_kegg 

# Settings for individual tools (rules). Add your own and make a pull request!
mlst_scheme: "automatic"

prokka_rfam: true # true (default) or false
prokka_compliant: true # true (default) or false

iqtree_bootstraps: 100
