mlst_scheme: "automatic"
input_genomes: "*.fna *.fa *.fasta *.fas" # Default value. Does not support advanced glob brace expansion. If you give multiple files or a single file has spaces or weird characters, it should be quoted within apostrophes.
annotator: "prokka" # prokka|bakta # Affects .faa used in dbcan, interproscan, diamond_kegg 




#asscom2_kraken2_db: "/cluster/projects/nn9864k/shared/databases/k2_pluspf_20210127"
#gtdbtk_data_path: "/cluster/projects/nn9864k/shared/databases/release207_v2"

# TODO: Find a way of having {base_variable} or some other word to point to the base directory.
# This is going to be quite hard if using the base_variable variable is not possible.
# database_path_busco: "${ASSCOM2_BASE}/databases/busco" # The directory where the following files reside: "file_versions.tsv  lineages/  placement_files/"
# database_path_gtdb: "{base_variable}/databases/gtdb" # The directory where the following files reside: "release207_v2" (or newer versions)
# database_path_checkm2: "{base_variable}/databases/checkm2" # The directory where the following files reside: "CheckM2_database/"
# database_path_kraken2: "{base_variable}/databases/kraken2" # The directory where the following files reside: hash.k2d"
