# TODO: This config should be saved in the results directory, so the user later knows which settings were used.

# --- Overall parameters affecting input and the whole pipeline -----


# File of file names.
# CHANGE_THIS_TO_ACTIVATE or change this to "path/to/fofn.txt" to activate: fofn.txt is a newline separated (like csv) list of input genomes to process. Takes precedence over parameter 'input_genomes'.
fofn: "CHANGE_THIS_TO_ACTIVATE"

# Input genomes
# In case fofn isn't set. Has a default value that means that it will pick up any genome in the terminals current working dir. If you give multiple files or a single file has spaces or weird characters, these characters should be escaped.
input_genomes: "*.fna *.fa *.fasta *.fas" 

# annotator
# Decide which annotator to use for downstream tools that use the output of either prokka or bakta.
annotator: "prokka" # prokka|bakta # Affects .faa used in dbcan, interproscan, diamond_kegg

output_directory: "results_comparem2"


# --- Parameter passthrough "set_" parameters for individual rules --

# These parameters are interpreted and any parameter can be added. Please check the documentation of each tool.
# Flag arguments are set with an empty string, and unset by removing the key altogether. 

set_interproscan--applications: "TIGRFAM,Hamap,Pfam"
set_interproscan--goterms: "" # flag
set_interproscan--pathways: "" # flag

set_iqtree--boot: 100
set_iqtree-m: GTR

# set_mlst--scheme: abaumannii # abaumannii achromobacter aeromonas afumigatus cdifficile efaecium hcinaedi hparasuis hpylori kpneumoniae leptospira saureus xfastidiosa yersinia ypseudotuberculosis yruckeri

set_panaroo--clean-mode: "sensitive" # Stringency mode.
set_panaroo--core_threshold: 0.95 # Core-genome sample threshold.
set_panaroo--threshold: 0.98 # Sequence identity threshold.
set_panaroo-a: core # Output alignment.
set_panaroo-f: 0.7 # Protein family sequence identity threshold.

set_prokka--compliant: "" # flag
set_prokka--kingdom: bacteria # archaea|bacteria|mitochondria|viruses
# set_prokka--rfam: "" # flag

set_treecluster--method: max_clade # avg_clade, leaf_dist_avg, leaf_dist_max, leaf_dist_min, length, length_clade, max, max_clade, med_clade, root_dist, single_linkage, single_linkage_cut, single_linkage_union, sum_branch, sum_branch_clade
set_treecluster--threshold: 0.05



# --- Parameters affecting the report -------------------------------

# Title. Used in the report.
# User can manually set the title. Otherwise the default is to use the name of the current working directory.
title: "CHANGE_THIS_TO_ACTIVATE" 

