
local-cores: 8 # front end / head node cores
cores: 2048 # cluster cores
jobs: 1000 # max parallel jobs


keep-going: true 
#rerun-incomplete: true
latency-wait: 120
keep-incomplete: true # Should be true for debugging rules.
rerun-triggers: "mtime" # only schedule jobs to rerun if there has been a change in mtime of input/output files. That is: ignore code changes

# This one could be cool to have working 
show-failed-logs: true


# ---- Conda/Mamba ----
use-conda: true


conda-frontend: 'mamba'
conda-prefix: '~/.asscom2/conda'



# ---- Sigma2 Saga SLURM specifics ----

cluster-cancel: "scancel"


cluster:
  mkdir -p results_ac2/logs/old &&
  sbatch
    --parsable
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=ac2_{rule}_{wildcards}
    --output=results_ac2/logs/%j-{rule}.out.log
    --error=results_ac2/logs/%j-{rule}.err.log
    --time={resources.runtime}
    --partition={resources.partition}
    --account=YOURACCOUNTNAMEHERE
    


default-resources:
  - mem_mb=1024
  - runtime='12h'
  - partition=normal
  
  