# Resources

cores: all


# Policies
keep-going: true 


keep-incomplete: false # true for debugging. Must be false for production, otherwise the user might get confusing --rerun-incomplete queries.
rerun-triggers: "mtime" # Only rerun on changes in modification time. Not on code hash changes.
rerun-incomplete: true





# Software deployment
software-deployment-method:
  - conda
  - apptainer

apptainer-prefix: '~/.comparem2/apptainer-prefix'
apptainer-args: '--bind "$COMPAREM2_BASE","$COMPAREM2_DATABASES","$(pwd)"' # Must also bind COMPAREM2_BASE so we can access databases and report scripts etc.

# Local setup for a typical workstation
resources:
  - mem_mb=256000
