#!/usr/bin/env python3
"""Generate the reference pages from the tool specs.

Writes `30 what analyses does it do.md` and `99 citation.md`.

v2 maintained both by hand and both drifted — the citation list kept entries for
dropped tools and missed added ones, and the analyses page documented default
parameters that no longer matched `config.yaml`. Everything these pages state is
already declared in `catalogue.py` and `guidance.py`, so they are derived.

    python docs/generate.py            # write the pages
    python docs/generate.py --check    # fail if either is out of date (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from comparem2.catalogue import CATALOGUE  # noqa: E402
from comparem2.guidance import GUIDANCE, citations  # noqa: E402
from comparem2.tools import Context, Scope  # noqa: E402

DOCS = Path(__file__).parent
GENERATED = "<!-- Generated by docs/generate.py. Do not edit by hand; edit\n     src/comparem2/catalogue.py and src/comparem2/guidance.py instead. -->"


def _example_command(tool) -> str:
    """The command as it would actually run, with placeholder paths."""
    ctx = Context(
        # Both placeholders are the real defaults, so the example is a command
        # a reader can paste — see `default_databases()` for the second.
        Path("results_comparem2"), Path("~/.comparem2/databases"), tool.threads,
        ("genome_A", "genome_B"),
        sample="genome_A" if tool.scope is Scope.GENOME else None,
        params=tool.params,
    )
    parts = list(tool.command(ctx))
    line = " ".join(parts)
    if tool.stdout_to_output:
        line += f" > {tool.outputs(ctx)[0]}"
    return line


# --- 30 what analyses does it do ------------------------------------

ANALYSES_HEADER = f"""

# What analyses does it do?

{GENERATED}

CompareM2 runs {len(CATALOGUE)} tools. Each is declared as one spec, and the
workflow is generated from those specs, so this page cannot fall out of step
with what actually runs.

Two kinds of tool:

  - **per genome** — runs once for each assembly
  - **per set** — runs once over all of them together

Use `--until` to run a subset. Dependencies come along automatically, so
`--until fasttree` also runs bakta and panaroo:

```bash
cm2 *.fna --until fasttree
```

"""


def analyses_page() -> str:
    parts = [ANALYSES_HEADER]

    parts.append("## Summary\n\n")
    parts.append("| Tool | Runs | Needs | Database |\n|---|---|---|---|\n")
    for tool in CATALOGUE:
        scope = "per genome" if tool.scope is Scope.GENOME else "per set"
        needs = ", ".join(f"`{n}`" for n in tool.needs) or "—"
        db = f"{tool.database.name} ({tool.database.human_size})" if tool.database else "—"
        parts.append(f"| [`{tool.name}`](#{tool.name}) | {scope} | {needs} | {db} |\n")

    total = CATALOGUE.install_size()
    unmeasured = CATALOGUE.unmeasured()
    note = f", plus {len(unmeasured)} of unknown size" if unmeasured else ""
    parts.append(
        f"\nRunning everything downloads **{total / 1e9:.1f} GB** of "
        f"databases{note}. `cm2` prints the total before downloading anything.\n\n"
    )

    for tool in CATALOGUE:
        entry = GUIDANCE[tool.name]
        parts.append(f"---\n\n## {tool.name}\n\n{entry.blurb}\n\n")
        parts.append(f"**How it works.** {entry.method}\n\n")

        scope = "once per genome" if tool.scope is Scope.GENOME else "once over the whole set"
        facts = [f"Runs {scope}", f"{tool.threads} thread" + ("s" if tool.threads > 1 else "")]
        if tool.needs:
            facts.append("after " + ", ".join(f"`{n}`" for n in tool.needs))
        if tool.database:
            facts.append(f"database `{tool.database.name}` ({tool.database.human_size})")
        if tool.isolated:
            facts.append("**own conda environment**")
        parts.append(" · ".join(facts) + "\n\n")

        parts.append(f"```\n{_example_command(tool)}\n```\n\n")

        if tool.params:
            parts.append("| Parameter | Default |\n|---|---|\n")
            for flag, value in tool.params:
                shown = f"`{value}`" if value else "*(flag)*"
                parts.append(f"| `--set {tool.name}{flag}=…` | {shown} |\n")
            parts.append("\n")

        parts.append("**Reading the output**\n\n")
        for label, text in entry.reading:
            parts.append(f"  - *{label}* — {text}\n")
        parts.append("\n**What it cannot tell you**\n\n")
        for caveat in entry.caveats:
            parts.append(f"  - {caveat}\n")
        parts.append("\n")

    parts.append(
        "---\n\n## Passthrough parameters\n\n"
        "Any argument can be forwarded to any tool with "
        "`--set <tool>--<flag>=<value>`. Naming one flag replaces only that "
        "flag; the tool's other defaults stay. A flag with no value is passed "
        "bare:\n\n"
        "```bash\ncm2 *.fna --set treecluster--threshold=0.1 "
        "--set skani-c=125\n```\n\n"
        "In v2 this was `set_<tool>--<flag>: <value>` in `config.yaml`.\n"
    )
    return "".join(parts)


# --- 99 citation ----------------------------------------------------

CITATION_HEADER = f"""

# Citing

{GENERATED}

## Citing CompareM2

If you use CompareM2, please cite:

  - Kobel C.M., Aho V.T.E., Øyås O., Nørskov-Lauritsen N., Woodcroft B.J.,
    Pope P.B. CompareM2 is a genomes-to-report pipeline for comparing microbial
    genomes. *Bioinformatics* 41(9), btaf517 (2025).
    [doi:10.1093/bioinformatics/btaf517](https://doi.org/10.1093/bioinformatics/btaf517)

CompareM2 is Open Access under the
[CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.

## Citing the tools

Please cite the tools you actually used. Every report lists them for its own run
in its *Methods and citations* section, generated from the same source as this
page. Where a tool wraps another method, both are listed — Mashtree wraps Mash,
Bakta calls Prodigal, Panaroo aligns with MAFFT.

"""

CITATION_FOOTER = """
## Tools with no publication

Two have none of their own, so the reference is to what should be credited
instead:

  - **MLST** — `tseemann/mlst` is unpublished; it types against PubMLST, so
    Jolley et al. 2018 is the citation. Cite the GitHub repository alongside it.
  - **snp-dists** — `tseemann/snp-dists` is unpublished and has no preprint.
    Cite the software DOI.
"""


def citation_page() -> str:
    parts = [CITATION_HEADER]
    for tool in CATALOGUE:
        entry = GUIDANCE[tool.name]
        parts.append(f"### {tool.name}\n\n")
        for citation in (entry.citation, *entry.also):
            parts.append(f"  - {citation.text}. "
                         f"[doi:{citation.doi}]({citation.url})\n")
            if citation.note:
                parts.append(f"    <br>*{citation.note}*\n")
        parts.append("\n")

    distinct = citations([t.name for t in CATALOGUE])
    parts.append(
        f"## BibTeX\n\nAll {len(distinct)} distinct references are in "
        "`papers/tools.bib` in the repository, fetched from Crossref rather "
        "than hand-typed.\n"
    )
    parts.append(CITATION_FOOTER)
    return "".join(parts)


PAGES = {
    "30 what analyses does it do.md": analyses_page,
    "99 citation.md": citation_page,
}


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true",
                   help="exit non-zero if any page is out of date")
    args = p.parse_args()

    stale = []
    for name, build in PAGES.items():
        path = DOCS / name
        text = build()
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
            continue
        path.write_text(text)
        print(f"wrote {name} ({len(text):,} bytes)")

    if args.check:
        if stale:
            print(f"out of date: {', '.join(stale)}\n"
                  f"run: python docs/generate.py", file=sys.stderr)
            return 1
        print(f"{len(PAGES)} generated pages up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
