name: immediate_1
on: workflow_dispatch

env:
  ASSCOM2_PROFILE: "profile/conda/local"


jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: asscom2
          environment-file: environment.yaml
      
      - name: check solution
        run: |
          mamba env export
      
      - name: test installation
        run: |
          python --version
          snakemake --version
          ./asscom2 --version
          ./asscom2 --help


      - name: dry run
        run: |
          ./asscom2 --config input_genomes="tests/E._faecium/*.fna" --dry-run

      - name: setup conda envs and copy
        run: |
          ./asscom2 --config input_genomes="tests/E._faecium/*.fna" --until copy && mamba clean --all -y


      - name: fast
        run: |
          ./asscom2 --config input_genomes="tests/E._faecium/*.fna" --until fast

