name: latest-dry-run
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
  



env:
  COMPAREM2_PROFILE: "profile/conda/default"



jobs:
  example-10-miniforge:
    name: Ex10 (${{ matrix.os }}, Miniforge)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: resources/env_current.yaml
          miniforge-version: latest


      - name: test installation
        run: |
          python --version
          snakemake --version
          ./comparem2 --help
          ./comparem2 --version
          ./comparem2 --cite
          ./comparem2 --status
          


      - name: dry run
        run: |
          ./comparem2 --dry-run
          rm -rf .snakemake results_comparem2

          ./comparem2 --until metadata
          rm -rf .snakemake results_comparem2
          
          touch dummy_1.fa; ./comparem2 --dry-run
          touch dummy_2.fa; ./comparem2 --dry-run
          touch dummy_3.fa; ./comparem2 --dry-run
          
          
          unzip tests/E._faecium/fna.zip
          ./comparem2 --config input_genomes="*.fna" --dry-run
          ./comparem2 --config input_genomes="*.fna" --until fast --dry-run
          ./comparem2 --config input_genomes="*.fna" --until isolate --dry-run
          ./comparem2 --config input_genomes="*.fna" --until meta --dry-run
          ./comparem2 --config input_genomes="*.fna" --until downloads --dry-run
          
          ls dummy_{2,3}.fa > fofn.txt; ./comparem2 --config fofn="fofn.txt" --dry-run   
          
