name: latest-dry-run
  
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
env:
  COMPAREM2_PROFILE: "profile/conda/default"

      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        #conda-version: "4.10.3"  # Specify the desired Conda version

    - name: Create Conda environment
      run: |
        conda env create -f resources/env_current.yaml  # Replace with your Conda environment file

    - name: Activate Conda environment
      shell: bash -l {0}  # Ensures we are using the login shell to initialize Conda
      run: |
        conda activate comparem2_launcher  # Replace with the name of your environment

    - name: Run tests
      shell: bash -l {0}  # Ensures we are using the login shell to initialize Conda
      run: |
        conda activate comparem2_launcher  # Ensure environment is active
        ./comparem2 --version  # Replace with your test command or other actions

        
    - name: test installation
      shell: bash -l {0} # Use login shell.
      run: |
        conda activate comparem2_launcher  # Ensure environment is active
        python --version
        snakemake --version
        ./comparem2 --help
        ./comparem2 --version
        ./comparem2 --cite
        ./comparem2 --status
          
