name: latest-dry-run
  
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
env:
  COMPAREM2_PROFILE: "profile/conda/default"

      

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        #conda-version: "4.10.3"  # Specify the desired Conda version

    - name: Create Conda environment
      run: |
        conda env create -f resources/env_current.yaml  # Replace with your Conda environment file

        
    - name: test installation
      #shell: bash -l {0} # Use login shell.
      run: |
        conda activate comparem2_launcher  # Ensure environment is active
        python --version
        snakemake --version
        ./comparem2 --help
        ./comparem2 --version
        ./comparem2 --cite
        
          

    - name: dry run
      #shell: bash -l {0}
      run: |
        conda activate comparem2_launcher
        ./comparem2 --dry-run
        rm -rf .snakemake results_comparem2

        ./comparem2 --until metadata
        rm -rf .snakemake results_comparem2
        
        touch dummy_1.fa; ./comparem2 --dry-run
        touch dummy_2.fa; ./comparem2 --dry-run
        touch dummy_3.fa; ./comparem2 --dry-run
        
        
        unzip tests/E._faecium/fna.zip
        ./comparem2 --config input_genomes="*.fna" add_ncbi="GCF_009734005.1,GCF_029023785.1" --dry-run
        ./comparem2 --config input_genomes="*.fna" add_ncbi="GCF_009734005.1,GCF_029023785.1" --until fast --dry-run
        ./comparem2 --config input_genomes="*.fna" add_ncbi="GCF_009734005.1,GCF_029023785.1" --until isolate --dry-run
        ./comparem2 --config input_genomes="*.fna" add_ncbi="GCF_009734005.1,GCF_029023785.1" --until meta --dry-run
        ./comparem2 --config input_genomes="*.fna" add_ncbi="GCF_009734005.1,GCF_029023785.1" --until downloads --dry-run
        
        ls dummy_{2,3}.fa > fofn.txt; ./comparem2 --config fofn="fofn.txt" --dry-run  
    
    - name: status 
      run: |
        conda activate comparem2_launcher
        ./comparem2 --status
