name: release_test1
on:
  push:
    paths:
      - '*'



jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: asscom2
          environment-file: .github/workflows/env.yaml
      
      - name: check solution
        run: |
          mamba env export
      
      - name: test installation
        run: |
          which asscom2
          asscom2 --help
