name: stable-fast
on:
  schedule:
    - cron: "10 0 * * 1"
  workflow_dispatch:
  

#env:
#  COMPAREM2_PROFILE: "profile/conda/default"


jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "<2"
          miniforge-version: "latest"
          channels: conda-forge,bioconda
          auto-activate-base: false
          activate-environment: comparem2_stable
          environment-file: resources/env_stable.yaml
      
      - name: check solution
        run: |
          mamba env export
      
      - name: test installation
        run: |
          python --version
          snakemake --version
          which comparem2
          comparem2 --help
          comparem2 --version
          comparem2 --cite
          comparem2 --status
          


# Runner can be started from thylakoid@johans:
# sudo -u ci-runner bash
# cd /mnt/evo/actions-runner/
# ./run.sh