name: stable-apptainer
on:
  schedule:
    - cron: "15 0 * * 1"
  workflow_dispatch:
  



# env:
#  COMPAREM2_PROFILE: "profile/conda/default"



jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "<2"
          miniforge-version: "latest"
          channels: conda-forge,bioconda
          auto-activate-base: false
          channel-priority: true
          activate-environment: comparem2_stable
          environment-file: resources/env_stable.yaml
      
      - name: check solution
        run: |
          mamba env export
      
      - name: test installation
        run: |
          python --version
          snakemake --version
          apptainer --version
          which comparem2
          comparem2 --help
          comparem2 --version
          comparem2 --cite
          comparem2 --status  
      
      

      - name: fast
        run: |
          unzip tests/E._faecium/fna.zip 
          comparem2 --config input_genomes="*.fna" --until fast
          
          tree results_comparem2
          rm -rf .snakemake results_comparem2 *.fna
          
      - name: full
        run: |
          unzip tests/E._faecium/fna.zip 
          comparem2 --config input_genomes="*.fna"
          
          tree results_comparem2
          rm -rf .snakemake results_comparem2 *.fna


      
      - name: dry run # With apptainer, dry run can't run without the image being pulled, so the dry run comes in the end instead.
        run: |
          comparem2 --dry-run
          rm -rf .snakemake results_comparem2

          comparem2 --until metadata
          rm -rf .snakemake results_comparem2
          
          touch dummy_1.fa; comparem2 --dry-run
          touch dummy_2.fa; comparem2 --dry-run
          touch dummy_3.fa; comparem2 --dry-run
          
          
          unzip tests/E._faecium/fna.zip
          comparem2 --config input_genomes="*.fna" --dry-run
          comparem2 --config input_genomes="*.fna" --until fast --dry-run
          comparem2 --config input_genomes="*.fna" --until isolate --dry-run
          comparem2 --config input_genomes="*.fna" --until meta --dry-run
          comparem2 --config input_genomes="*.fna" --until downloads --dry-run
          
          ls dummy_{2,3}.fa > fofn.txt; comparem2 --config fofn="fofn.txt" --dry-run   
          rm -rf .snakemake results_comparem2 *.fna
          
          
          
      

# Runner can be started from thylakoid@johans:
# sudo -u ci-runner bash
# cd /mnt/evo/actions-runner/
# ./run.sh